server:
  port: 8096  #端口号

#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: city_roast_token_swap
#          uri: http://localhost:8080
#          predicates:
#            - Path=/city-roast/token-swap
#            - Method=GET